[build]
  command = "npm run build"
  publish = "build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self';"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=()"

[[redirects]]
  from = "/*.php"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.asp"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.aspx"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.cgi"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.pl"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.jsp"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.sh"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.bak"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.old"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.tmp"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.swp"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.sql"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.env"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.git"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.htaccess"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.htpasswd"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.ini"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*.conf"
  to = "/404"
  status = 404